### ISSUE TITLE
Display brand image on card

### ISSUE THREAD

**Issue by hafeefshaik** [nauvalazhar/my-login#1]
Hi,

I am new to CSS. Can you please help in displaying brand image on the card as mentioned below screenshot.

![image](https://user-images.githubusercontent.com/32909535/40057976-65481a6a-586d-11e8-91fa-a5d16c4f2d04.png)

The image should appear on the front, as of now it's behind the card.

**Comment by hafeefshaik** [comment]
reference link: https://bootsnipp.com/snippets/WaP9O

**Comment by nauvalazhar** [comment]
Hi, please post your code.

**Comment by hafeefshaik** [comment]
Same code and CSS as mentioned in index.html, except the image. Please let me know still you need the code.

https://github.com/nauvalazhar/my-login/blob/master/index.html

**Comment by nauvalazhar** [comment]
K, you need to add these properties to the `.my-login-page .brand` selector.
```css
position: relative;
z-index: 1;
```

**Comment by hafeefshaik** [comment]
@nauvalazhar Thanks, brother.
