### ISSUE TITLE
Internet Explorer 11, 10 issue

### ISSUE THREAD

**Issue by akshinmustafayev** [nauvalazhar/my-login#4]
Login form "https://nauvalazhar.github.io/my-login/index.html" shows on the right site in Internet explorer 11, 10.

Adding **style="margin:0px;"** to **<div class="card-wrapper"'>** fixes that, but breaks page on other versions of Internet explorer

**Comment by nauvalazhar** [comment]
Hi, thank you for creating an issue.
To fix this, I removed the property `margin: 0 auto;` in the `.my-login-page .card-wrapper` selector. Successfully fixing issue on IE 11, I haven't tested it on IE 10.

**Comment by akshinmustafayev** [comment]
thank for your reply
